site_name: AlignAI

  
theme:
  name: material
 # custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
nav:
  - 首页: "index.md"
  - 研报: 

      - Google MedGemma: "research/Google MedGemma.md"
      - 图像去雾: "research/图像去雾算法研究_.md"
      - 点云转CAD: "research/点云转CAD.md"
      - 倾斜摄影:
        - 单目重建: "research/倾斜摄影单目重建.md"
      - colmap集成SuperPoint: "research/COLMAP替换SuperPoint和SuperGlue_.md"
      - AI医学综述: "research/AI医学辅助诊断算法综述_.md"
      - 口腔医学:
        - 专家共识: "research/口腔医学/专家共识.md"
        - IEEE口腔AI论文: "research/口腔医学/IEEE口腔AI论文.md"
  - 项目: 
      - MASt3R-SLAM: "projects/MASt3R-SLAM.md"
      - 基础环境安装: "projects/环境安装.md"
      - VTKexamples: "projects/VTKexamples.md"
      - GB28281: "projects/GB28281.md"
      - Teaser++点云配准: "projects/Teaser++.md"
      - 在线Demo: "projects/在线Demo.md"
      - 静态页: "projects/静态页.md"
  - "license.md"