name: ci
on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Build site
        run: mkdocs build

      - name: Install Aliyun OSS CLI
        run: |
          # 安装阿里云 CLI (包含 ossutil)
          wget http://gosspublic.alicdn.com/ossutil/1.7.1/ossutil64 -O /usr/local/bin/ossutil
          chmod +x /usr/local/bin/ossutil
          ossutil --version

      

      - name: Upload to Aliyun OSS
        env:
          ENDPOINT: ${{ secrets.ALIYUN_ENDPOINT }}
          BUCKET: ${{ secrets.ALIYUN_BUCKET_NAME }}
          ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        run: |
          # 配置 ossutil
          ossutil config -i $ACCESS_KEY_ID -k $ACCESS_KEY_SECRET -e $ENDPOINT

          # 递归上传整个 site 目录到 OSS
          ossutil cp -r site/ oss://$BUCKET/ --update
          
      # 部署到 Vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25 # 或者最新的版本
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # 必需
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}   # 必需
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # 必需
          vercel-args: '--prod' # 传递给 vercel deploy 的额外参数，例如 --prod 表示部署到生产环境
          working-directory: ./site # 如果你的项目在子目录


      # edgeone 限制文件尺寸25M,需要移除search文件
      - name: Remove search folder
        run: rm -rf ./site/search
      - name: Deploy to EdgeOne Pages
        run: npx edgeone pages deploy ./site -n alignai -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}
